const marvelData = [
    {
        "position": 1,
        "title": "Eyes of Wakanda",
        "year": "2025",
        "runtime": "2 h 5 min",
        "description": "Wakandan warriors who, throughout history, have traveled the world to retrieve dangerous vibranium artifacts.\r\n- Episode 1: 1260 BC (32 min)\r\n- Episode 2: 1200 BC (32 min)\r\n- Episode 3: 1400 (31 min)\r\n- Episode 4: March 1896 (30 min)",
        "timeline": "1260 BC - 1896",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios Animation",
        "image": "Eyes-of-Wakanda"
    },
    {
        "position": 2,
        "title": "Captain America: The First Avenger",
        "year": "2011",
        "runtime": "2 h 6 min",
        "description": "Steve Rogers, a rejected military soldier, transforms into Captain America after taking a dose of a Super-Soldier serum. But being Captain America comes at a price as he attempts to take down a warmonger and a terrorist organization.",
        "timeline": "March 1942-March 1945 | 2011",
        "universe": "Earth-616",
        "phase": "Phase 1",
        "studio": "Marvel Studios",
        "image": "Captain-America-The-First-Avenger"
    },
    {
        "position": 3,
        "title": "Marvel One-Shot: Agent Carter",
        "year": "2013",
        "runtime": "16 min",
        "description": "Agent Carter seeks the enigmatic Zodiac and also battles her misogynistic, bureaucratic boss. Frustrated at being marginalized at work, Peggy Carter goes on an unauthorized solo field mission.",
        "timeline": "1946",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "Marvel-One-Shot-Agent-Carter"
    },
    {
        "position": 4,
        "title": "Agent Carter",
        "year": "2015-2016",
        "runtime": "13 h 14 min",
        "description": "In 1946, Peggy Carter is relegated to secretarial duties in the Strategic Scientific Reserve (SSR). When Howard Stark is accused of treason, he secretly recruits Peggy to clear his name with the help of his butler, Edwin Jarvis.\r\n- Season 1: April-May 1946 (5 h 49 min) \r\n- Season 2: July 1947 (7 h 25 min)",
        "timeline": "April 1946 - July 1947",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Agent-Carter"
    },
    {
        "position": 5,
        "title": "X-Men: First Class",
        "year": "2011",
        "runtime": "2 h 13 min",
        "description": "In the 1960s, superpowered humans Charles Xavier and Erik Lensherr work together to find others like them, but Erik's vengeful pursuit of an ambitious mutant who ruined his life causes a schism to divide them.",
        "timeline": "1962",
        "universe": "Earth-10005",
        "phase": "other",
        "studio": "20th Century Fox",
        "image": "X-Men-First-Class"
    },
    {
        "position": 6,
        "title": "The Fantastic Four: First Steps",
        "year": "2025",
        "runtime": "1 h 56 min",
        "description": "Forced to balance their roles as heroes with the strength of their family bond, the Fantastic Four must defend Earth from a ravenous space god called Galactus and his enigmatic herald, the Silver Surfer.",
        "timeline": "February 1964 - February 1965",
        "universe": "Earth-828",
        "phase": "Phase 6",
        "studio": "Marvel Studios",
        "image": "The-Fantastic-Four-First-Steps"
    },
    {
        "position": 7,
        "title": "X-Men: Days of Future Past",
        "year": "2014",
        "runtime": "2 h 13 min",
        "description": "The X-Men send Wolverine to the past in a desperate effort to change history and prevent an event that results in doom for both humans and mutants.",
        "timeline": "1973 | 2023",
        "universe": "Earth-10005",
        "phase": "other",
        "studio": "20th Century Fox",
        "image": "X-Men-Days-of-Future-Past"
    },
    {
        "position": 8,
        "title": "X-Men Origins: Wolverine",
        "year": "2009",
        "runtime": "1 h 48 min",
        "description": "The early years of James Logan, featuring his rivalry with his brother Victor Creed, his service in the special forces team Weapon X, and his experimentation into the metal-lined mutant Wolverine.",
        "timeline": "1979",
        "universe": "Earth-10005",
        "phase": "other",
        "studio": "20th Century Fox",
        "image": "X-Men-Origins-Wolverine"
    },
    {
        "position": 9,
        "title": "X-Men: Apocalypse",
        "year": "2016",
        "runtime": "2 h 25 min",
        "description": "In the 1980s, the X-Men must defeat an ancient all-powerful mutant, En Sabah Nur, who intends to thrive by bringing destruction to the world.",
        "timeline": "1983",
        "universe": "Earth-10005",
        "phase": "other",
        "studio": "20th Century Fox",
        "image": "X-Men-Apocalypse"
    },
    {
        "position": 10,
        "title": "Howard the Duck",
        "year": "1986",
        "runtime": "1 h 50 m",
        "description": "A sarcastic humanoid duck is pulled from his homeworld to Earth where he must stop an alien invasion with the help of a nerdy scientist and a struggling female rock singer.",
        "timeline": "1986",
        "universe": "",
        "phase": "other",
        "studio": "Universal Pictures",
        "image": "Howard-the-Duck"
    },
    {
        "position": 11,
        "title": "X-Men: Dark Phoenix",
        "year": "2019",
        "runtime": "1 h 56 min",
        "description": "Jean Grey begins to develop incredible powers that corrupt and turn her into a Dark Phoenix, causing the X-Men to have to decide if her life is worth more than all of humanity.",
        "timeline": "1992",
        "universe": "Earth-10005",
        "phase": "other",
        "studio": "20th Century Fox",
        "image": "X-Men-Dark-Phoenix"
    },
    {
        "position": 12,
        "title": "Captain Marvel",
        "year": "2019",
        "runtime": "2 h 7 min",
        "description": "Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races.",
        "timeline": "June 1995",
        "universe": "Earth-616",
        "phase": "Phase 3",
        "studio": "Marvel Studios",
        "image": "Captain-Marvel"
    },
    {
        "position": 13,
        "title": "X-Men '97",
        "year": "2024-",
        "runtime": "10 h 38 min",
        "description": "A band of mutants use their uncanny gifts to protect a world that hates and fears them; they're challenged like never before, forced to face a dangerous and unexpected new future.",
        "timeline": "1997",
        "universe": "Earth-92131",
        "phase": "other",
        "studio": "Marvel Studios Animation",
        "image": "X-Men-97"
    },
    {
        "position": 14,
        "title": "Blade",
        "year": "1998",
        "runtime": "2 h",
        "description": "A half-vampire, half-mortal man becomes a protector of the mortal race, while slaying evil vampires.",
        "timeline": "1998",
        "universe": "Earth-26320",
        "phase": "other",
        "studio": "New Line Cinema",
        "image": "Blade"
    },
    {
        "position": 15,
        "title": "X-Men",
        "year": "2000",
        "runtime": "1 h 45 min",
        "description": "In a world where mutants (evolved super-powered humans) exist and are discriminated against, two groups form for an inevitable clash: the supremacist Brotherhood, and the pacifist X-Men.",
        "timeline": "2000",
        "universe": "Earth-10005",
        "phase": "other",
        "studio": "20th Century Fox",
        "image": "X-Men"
    },
    {
        "position": 16,
        "title": "Blade II",
        "year": "2002",
        "runtime": "1 h 57 min",
        "description": "Blade forms an uneasy alliance with the vampire council in order to combat the Reapers, who are feeding on vampires.",
        "timeline": "2002",
        "universe": "Earth-26320",
        "phase": "other",
        "studio": "New Line Cinema",
        "image": "Blade-II"
    },
    {
        "position": 17,
        "title": "Spider-Man",
        "year": "2002",
        "runtime": "2 h 1 min",
        "description": "A shy teenager is bitten by a genetically modified spider and uses his new spider-like abilities to fight injustice as a masked superhero.",
        "timeline": "2002",
        "universe": "Earth-96283",
        "phase": "other",
        "studio": "Columbia Pictures",
        "image": "Spider-Man"
    },
    {
        "position": 18,
        "title": "Madame Web",
        "year": "2024",
        "runtime": "1 h 56 min",
        "description": "Forced to confront her past, Cassandra Webb, a Manhattan paramedic that may have clairvoyant abilities, forms a relationship with three young women destined for powerful futures, if they can survive their threatening present.",
        "timeline": "2003",
        "universe": "Earth-688B",
        "phase": "other",
        "studio": "Columbia Pictures",
        "image": "Madame-Web"
    },
    {
        "position": 19,
        "title": "Hulk",
        "year": "2003",
        "runtime": "2 h 18 min",
        "description": "Bruce Banner, a genetics researcher with a tragic past, suffers a lab accident that makes him transform into a raging, giant green monster when angered, making him a target of forces seeking to abuse his power.",
        "timeline": "2003",
        "universe": "Earth-400083",
        "phase": "other",
        "studio": "Universal Pictures",
        "image": "Hulk"
    },
    {
        "position": 20,
        "title": "Daredevil",
        "year": "2003",
        "runtime": "1 h 43 min",
        "description": "A man blinded by toxic waste which also enhanced his remaining senses fights crime as an acrobatic martial arts superhero.",
        "timeline": "2003",
        "universe": "Earth-701306",
        "phase": "other",
        "studio": "20th Century Fox",
        "image": "Daredevil_movie"
    },
    {
        "position": 21,
        "title": "X-Men 2",
        "year": "2003",
        "runtime": "2 h 14 min",
        "description": "When anti-mutant Colonel William Stryker kidnaps Professor X and attacks his school, the X-Men must ally with their archenemy Magneto to stop him.",
        "timeline": "2003",
        "universe": "Earth-10005",
        "phase": "other",
        "studio": "20th Century Fox",
        "image": "X-Men-2"
    },
    {
        "position": 22,
        "title": "The Punisher",
        "year": "2004",
        "runtime": "2 h 4 min",
        "description": "An undercover FBI agent becomes a vigilante and sets out to unleash his wrath upon the corrupt businessman who slaughtered his entire family at a reunion.",
        "timeline": "2004",
        "universe": "Earth-58732",
        "phase": "other",
        "studio": "Lionsgate",
        "image": "The-Punisher"
    },
    {
        "position": 23,
        "title": "Spider-Man 2",
        "year": "2004",
        "runtime": "2 h 7 min",
        "description": "Peter Parker is beset with troubles in his failing personal life as he battles a former brilliant scientist named Otto Octavius.",
        "timeline": "2004",
        "universe": "Earth-96283",
        "phase": "other",
        "studio": "Columbia Pictures",
        "image": "Spider-Man-2"
    },
    {
        "position": 24,
        "title": "Blade: Trinity",
        "year": "2004",
        "runtime": "1 h 53 min",
        "description": "Blade, now a wanted man by the FBI, must join forces with the Nightstalkers to face his most challenging enemy yet: Dracula.",
        "timeline": "2004",
        "universe": "Earth-26320",
        "phase": "other",
        "studio": "New Line Cinema",
        "image": "Blade-Trinity"
    },
    {
        "position": 25,
        "title": "Elektra",
        "year": "2005",
        "runtime": "1 h 37 min",
        "description": "An assassin's change of heart leads her into a war against an evil crime syndicate.",
        "timeline": "2005",
        "universe": "Earth-701306",
        "phase": "other",
        "studio": "20th Century Fox",
        "image": "Elektra"
    },
    {
        "position": 26,
        "title": "Fantastic Four",
        "year": "2005",
        "runtime": "1 h 45 min",
        "description": "A group of astronauts gain superpowers after a cosmic radiation exposure and must use them to oppose the plans of their enemy, Doctor Victor Von Doom.",
        "timeline": "2005",
        "universe": "Earth-121698",
        "phase": "other",
        "studio": "20th Century Fox",
        "image": "Fantastic-Four"
    },
    {
        "position": 27,
        "title": "X-Men: The Last Stand",
        "year": "2006",
        "runtime": "1 h 45 min",
        "description": "The human government develops a cure for mutations, and Jean Grey becomes a darker uncontrollable persona called the Phoenix who allies with Magneto, causing escalation into an all-out battle for the X-Men.",
        "timeline": "2006",
        "universe": "Earth-10005",
        "phase": "other",
        "studio": "20th Century Fox",
        "image": "X-Men-The-Last-Stand"
    },
    {
        "position": 28,
        "title": "Ghost Rider",
        "year": "2007",
        "runtime": "1 h 50 min",
        "description": "A motorcycle stuntman who sold his soul becomes a supernatural agent of vengeance.",
        "timeline": "2007",
        "universe": "Earth-121347",
        "phase": "other",
        "studio": "Columbia Pictures",
        "image": "Ghost-Rider"
    },
    {
        "position": 29,
        "title": "Spider-Man 3",
        "year": "2007",
        "runtime": "2 h 19 m",
        "description": "A strange black entity from another world bonds with Peter Parker and causes inner turmoil as he contends with new villains, temptations, and revenge.",
        "timeline": "2007",
        "universe": "Earth-96283",
        "phase": "other",
        "studio": "Columbia Pictures",
        "image": "Spider-Man-3"
    },
    {
        "position": 30,
        "title": "Fantastic 4: Rise of the Silver Surfer",
        "year": "2007",
        "runtime": "1 h 32 min",
        "description": "The Fantastic Four learn that they aren't the only super-powered beings in the universe when they square off against the powerful Silver Surfer and the planet-eating Galactus.",
        "timeline": "2007",
        "universe": "Earth-121698",
        "phase": "other",
        "studio": "20th Century Fox",
        "image": "Fantastic-4-Rise-of-the-Silver-Surfer"
    },
    {
        "position": 31,
        "title": "Iron Man",
        "year": "2008",
        "runtime": "2 h 7 min",
        "description": "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.\r\nOriginaly happened in 2008 but officially moved to 2010 to align with the timeline.",
        "timeline": "January-May 2010",
        "universe": "Earth-616",
        "phase": "Phase 1",
        "studio": "Marvel Studios",
        "image": "Iron-Man"
    },
    {
        "position": 32,
        "title": "Iron Man 2",
        "year": "2010",
        "runtime": "2 h 5 min",
        "description": "With the world now aware of his identity as Iron Man, Tony Stark must contend with both his declining health and a vengeful madman with ties to his father's legacy.",
        "timeline": "2011",
        "universe": "Earth-616",
        "phase": "Phase 1",
        "studio": "Marvel Studios",
        "image": "Iron-Man-2"
    },
    {
        "position": 33,
        "title": "The Incredible Hulk",
        "year": "2008",
        "runtime": "1 h 52 min",
        "description": "Bruce Banner, a scientist on the run from the U.S. Government, must find a cure for the monster he turns into whenever he loses his temper.\r\nOriginaly happened in 2007-2009 but officially moved by 2 years to align with the timeline.",
        "timeline": "2011",
        "universe": "Earth-616",
        "phase": "Phase 1",
        "studio": "Marvel Studios",
        "image": "The-Incredible-Hulk"
    },
    {
        "position": 34,
        "title": "Marvel One-Shot: The Consultant",
        "year": "2011",
        "runtime": "4 min",
        "description": "Agents Coulson and Sitwell plan to derail General Thaddeus Thunderbolt Ross from interfering with S.H.I.E.L.D. affairs with a very special person. Technically should be watched just before the post credit scene of The Incredible Hulk.",
        "timeline": "2011",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "Marvel-One-Shot-The-Consultant"
    },
    {
        "position": 35,
        "title": "Marvel One-Shot: A Funny Thing Happened on the Way to Thor's Hammer",
        "year": "2011",
        "runtime": "4 min",
        "description": "Agent Coulson stops at a convenience store and deals with a coincidental robbery during his visit.",
        "timeline": "2011",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "Marvel-One-Shot-A-Funny-Thing-Happened-on-the-Way-to-Thor-s-Hammer"
    },
    {
        "position": 36,
        "title": "Thor",
        "year": "2011",
        "runtime": "1 h 57 min",
        "description": "The powerful but arrogant god Thor is cast out of Asgard to live amongst humans in Midgard (Earth), where he soon becomes one of their finest defenders.",
        "timeline": "2011",
        "universe": "Earth-616",
        "phase": "Phase 1",
        "studio": "Marvel Studios",
        "image": "Thor"
    },
    {
        "position": 37,
        "title": "Ghost Rider: Spirit of Vengeance",
        "year": "2011",
        "runtime": "1 h 36 min",
        "description": "Johnny Blaze, tortured by the Ghost Rider's curse, gets a chance of redemption through protecting the Devil's son, whose father is pursuing him.",
        "timeline": "2011",
        "universe": "Earth-121347",
        "phase": "other",
        "studio": "Columbia Pictures",
        "image": "Ghost-Rider-Spirit-of-Vengeance"
    },
    {
        "position": 38,
        "title": "The Avengers",
        "year": "2012",
        "runtime": "2 h 26 min",
        "description": "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
        "timeline": "May 2012",
        "universe": "Earth-616",
        "phase": "Phase 1",
        "studio": "Marvel Studios",
        "image": "The-Avengers"
    },
    {
        "position": 39,
        "title": "Marvel One-Shot: Item 47",
        "year": "2012",
        "runtime": "12 min",
        "description": "S.H.I.E.L.D. agent Sitwell is assigned to recover an abandoned Chitauri weapon being used by a young couple robbing a bank.",
        "timeline": "May 2012",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "Marvel-One-Shot-Item-47"
    },
    {
        "position": 40,
        "title": "The Amazing Spider-Man",
        "year": "2012",
        "runtime": "2 h 16 min",
        "description": "After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.",
        "timeline": "January 2012",
        "universe": "Earth-120703",
        "phase": "other",
        "studio": "Columbia Pictures",
        "image": "The-Amazing-Spider-Man"
    },
    {
        "position": 41,
        "title": "Agents of S.H.I.E.L.D.",
        "year": "2013-2020",
        "runtime": "5 h 11 min",
        "description": "The missions of the Strategic Homeland Intervention, Enforcement and Logistics Division.\r\n- Season 1, Episode 1-7",
        "timeline": "September-November 2013",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Agents-of-S-H-I-E-L-D-"
    },
    {
        "position": 42,
        "title": "Thor: The Dark World",
        "year": "2013",
        "runtime": "1 h 55 min",
        "description": "When the Dark Elves attempt to plunge the universe into darkness, Thor must embark on a perilous and personal journey that will reunite him with doctor Jane Foster.",
        "timeline": "November 2013",
        "universe": "Earth-616",
        "phase": "Phase 2",
        "studio": "Marvel Studios",
        "image": "Thor-The-Dark-World"
    },
    {
        "position": 43,
        "title": "Agents of S.H.I.E.L.D.",
        "year": "2013-2020",
        "runtime": "3 h 41 min",
        "description": "The missions of the Strategic Homeland Intervention, Enforcement and Logistics Division.\r\n-  Season 1, Episode 8-12",
        "timeline": "November-December 2013",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Agents-of-S-H-I-E-L-D-"
    },
    {
        "position": 44,
        "title": "The Wolverine",
        "year": "2013",
        "runtime": "2 h 7 min",
        "description": "Wolverine comes to Japan to meet an old friend whose life he saved years ago, and gets embroiled in a conspiracy involving yakuza and mutants.",
        "timeline": "2013",
        "universe": "Earth-10005",
        "phase": "other",
        "studio": "20th Century Fox",
        "image": "The-Wolverine"
    },
    {
        "position": 45,
        "title": "Iron Man 3",
        "year": "2013",
        "runtime": "2 h 12 min",
        "description": "When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.",
        "timeline": "December 2013-January 2014",
        "universe": "Earth-616",
        "phase": "Phase 2",
        "studio": "Marvel Studios",
        "image": "Iron-Man-3"
    },
    {
        "position": 46,
        "title": "Marvel One-Shot: All Hail the King",
        "year": "2014",
        "runtime": "14 min",
        "description": "A documentary filmmaker interviews the now-famous Trevor Slattery from behind bars.",
        "timeline": "2014",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "Marvel-One-Shot-All-Hail-the-King"
    },
    {
        "position": 47,
        "title": "Agents of S.H.I.E.L.D.",
        "year": "2013-2020",
        "runtime": "2 h 56 min",
        "description": "The missions of the Strategic Homeland Intervention, Enforcement and Logistics Division.\r\n- Season 1, Episode 13-16",
        "timeline": "March-April 2014",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Agents-of-S-H-I-E-L-D-"
    },
    {
        "position": 48,
        "title": "Captain America: The Winter Soldier",
        "year": "2014",
        "runtime": "2 h 19 min",
        "description": "As Steve Rogers struggles to embrace his role in the modern world, he teams up with a fellow Avenger and S.H.I.E.L.D agent, Black Widow, to battle a new threat from history: an assassin known as the Winter Soldier.",
        "timeline": "April 2014",
        "universe": "Earth-616",
        "phase": "Phase 2",
        "studio": "Marvel Studios",
        "image": "Captain-America-The-Winter-Soldier"
    },
    {
        "position": 49,
        "title": "Agents of S.H.I.E.L.D.",
        "year": "2013-2020",
        "runtime": "6 h",
        "description": "The missions of the Strategic Homeland Intervention, Enforcement and Logistics Division.\r\n- Season 1 Episode 17-22 (4 h 30 min)\r\n- Season 2, Episode 1-2 (1 h 30 min)",
        "timeline": "April 2014",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Agents-of-S-H-I-E-L-D-"
    },
    {
        "position": 50,
        "title": "The Amazing Spider-Man 2",
        "year": "2014",
        "runtime": "2 h 21 min",
        "description": "When New York is put under siege by Oscorp, it is up to Spider-Man to save the city he swore to protect as well as his loved ones.",
        "timeline": "June 2014-December 2014",
        "universe": "Earth-120703",
        "phase": "other",
        "studio": "Columbia Pictures",
        "image": "The-Amazing-Spider-Man-2"
    },
    {
        "position": 51,
        "title": "Guardians of the Galaxy",
        "year": "2014",
        "runtime": "2 h 3 min",
        "description": "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.",
        "timeline": "2014",
        "universe": "Earth-616",
        "phase": "Phase 2",
        "studio": "Marvel Studios",
        "image": "Guardians-of-the-Galaxy"
    },
    {
        "position": 52,
        "title": "I Am Groot",
        "year": "2022-2023",
        "runtime": "6 min",
        "description": "A series of shorts featuring the seedling Groot along with several new and unusual characters.\r\n- Season 1, Episode 1",
        "timeline": "2014",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios Animation",
        "image": "I-Am-Groot"
    },
    {
        "position": 53,
        "title": "Agents of S.H.I.E.L.D.",
        "year": "2013-2020",
        "runtime": "45 min",
        "description": "The missions of the Strategic Homeland Intervention, Enforcement and Logistics Division.\r\n- Season 2, Episode 3",
        "timeline": "2014",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Agents-of-S-H-I-E-L-D-"
    },
    {
        "position": 54,
        "title": "Guardians of the Galaxy: Vol. 2",
        "year": "2017",
        "runtime": "2 h 18 min",
        "description": "The Guardians struggle to keep together as a team while dealing with their personal family issues, notably Star-Lord's encounter with his father, the ambitious celestial being Ego.\r\n- Two months after Guardians of the Galaxy",
        "timeline": "2014",
        "universe": "Earth-616",
        "phase": "Phase 3",
        "studio": "Marvel Studios",
        "image": "Guardians-of-the-Galaxy-Vol-2"
    },
    {
        "position": 55,
        "title": "I Am Groot 2",
        "year": "2022-2023",
        "runtime": "49 min",
        "description": "A series of shorts featuring the seedling Groot along with several new and unusual characters.\r\n- Season 1, Episode 2-5 (24 min)\r\n- Season 2 (25 min)",
        "timeline": "2014",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios Animation",
        "image": "I-Am-Groot-2"
    },
    {
        "position": 56,
        "title": "Daredevil",
        "year": "2015-2018",
        "runtime": "12 h 5 min",
        "description": "A blind lawyer by day, vigilante by night. Matt Murdock fights the crime of New York as Daredevil.\r\n- Season 1",
        "timeline": "2014",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Daredevil"
    },
    {
        "position": 57,
        "title": "Jessica Jones",
        "year": "2015-2019",
        "runtime": "11 h 35 min",
        "description": "Following the tragic end of her brief superhero career, Jessica Jones tries to rebuild her life as a private investigator, dealing with cases involving people with remarkable abilities in New York City.\r\n- Season 1",
        "timeline": "January-March 2015",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Jessica-Jones"
    },
    {
        "position": 58,
        "title": "Agents of S.H.I.E.L.D.",
        "year": "2013-2020",
        "runtime": "11 h 53 min",
        "description": "The missions of the Strategic Homeland Intervention, Enforcement and Logistics Division.\r\n- Season 2, Episode 4-19",
        "timeline": "March-April 2015",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Agents-of-S-H-I-E-L-D-"
    },
    {
        "position": 59,
        "title": "Avengers: Age of Ultron",
        "year": "2015",
        "runtime": "2 h 24 min",
        "description": "When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong and it's up to Earth's mightiest heroes to stop the villainous Ultron from enacting his terrible plan.",
        "timeline": "April 2015",
        "universe": "Earth-616",
        "phase": "Phase 2",
        "studio": "Marvel Studios",
        "image": "Avengers-Age-of-Ultron"
    },
    {
        "position": 60,
        "title": "Agents of S.H.I.E.L.D.",
        "year": "2013-2020",
        "runtime": "2 h 15 min",
        "description": "The missions of the Strategic Homeland Intervention, Enforcement and Logistics Division.\r\n- Season 2, Episode 20-22",
        "timeline": "April 2015",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Agents-of-S-H-I-E-L-D-"
    },
    {
        "position": 61,
        "title": "WHIH News Front",
        "year": "2015-2016",
        "runtime": "10 min",
        "description": "A series of news bulletins on events within the Marvel Cinematic Universe, as presented by reporter Christine Everhart.\r\n- Season 1",
        "timeline": "July 2015",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "WHIH-News-Front"
    },
    {
        "position": 62,
        "title": "Ant-Man",
        "year": "2015",
        "runtime": "2 h",
        "description": "Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, pull off a plan that will save the world.",
        "timeline": "August 2015",
        "universe": "Earth-616",
        "phase": "Phase 2",
        "studio": "Marvel Studios",
        "image": "Ant-Man"
    },
    {
        "position": 63,
        "title": "Agents of S.H.I.E.L.D.",
        "year": "2013-2020",
        "runtime": "2 h 12 min",
        "description": "The missions of the Strategic Homeland Intervention, Enforcement and Logistics Division.\r\n- Season 3, Episode 1-3",
        "timeline": "October 2015",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Agents-of-S-H-I-E-L-D-"
    },
    {
        "position": 64,
        "title": "Luke Cage",
        "year": "2016-2018",
        "runtime": "3 h 44 min",
        "description": "When a sabotaged experiment gives him super strength and unbreakable skin, Luke Cage becomes a fugitive attempting to rebuild his life in Harlem and must confront his past and fight a battle for the heart of his city.\r\n- Season 1, Episode 1-4",
        "timeline": "October 2015",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Luke-Cage"
    },
    {
        "position": 65,
        "title": "Daredevil 2",
        "year": "2015-2018",
        "runtime": "11 h 51 min",
        "description": "A blind lawyer by day, vigilante by night. Matt Murdock fights the crime of New York as Daredevil.\r\n- Season 2",
        "timeline": "October-November 2015",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Daredevil-2"
    },
    {
        "position": 66,
        "title": "Luke Cage",
        "year": "2016-2018",
        "runtime": "1 h 46 min",
        "description": "When a sabotaged experiment gives him super strength and unbreakable skin, Luke Cage becomes a fugitive attempting to rebuild his life in Harlem and must confront his past and fight a battle for the heart of his city.\r\n- Season 1, Episode 5-6",
        "timeline": "November 2015",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Luke-Cage"
    },
    {
        "position": 67,
        "title": "Agents of S.H.I.E.L.D.",
        "year": "2013-2020",
        "runtime": "3 h 45 min",
        "description": "The missions of the Strategic Homeland Intervention, Enforcement and Logistics Division.\r\n- Season 3, Episode 4-8",
        "timeline": "November 2015",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Agents-of-S-H-I-E-L-D-"
    },
    {
        "position": 68,
        "title": "Luke Cage",
        "year": "2016-2018",
        "runtime": "6 h 14 min",
        "description": "When a sabotaged experiment gives him super strength and unbreakable skin, Luke Cage becomes a fugitive attempting to rebuild his life in Harlem and must confront his past and fight a battle for the heart of his city.\r\n- Season 1, Episode 7-13",
        "timeline": "November-December 2015",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Luke-Cage"
    },
    {
        "position": 69,
        "title": "Agents of S.H.I.E.L.D.",
        "year": "2013-2020",
        "runtime": "1 h 30 min",
        "description": "The missions of the Strategic Homeland Intervention, Enforcement and Logistics Division.\r\n- Season 3, Episode 9-10",
        "timeline": "December 2015",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Agents-of-S-H-I-E-L-D-"
    },
    {
        "position": 70,
        "title": "Iron Fist",
        "year": "2017-2018",
        "runtime": "12 h 5 min",
        "description": "A young man is bestowed with incredible martial arts skills and a mystical force known as the Iron Fist.\r\n- Season 1",
        "timeline": "February-March 2016",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Iron-Fist"
    },
    {
        "position": 71,
        "title": "Agents of S.H.I.E.L.D.",
        "year": "2013-2020",
        "runtime": "5 h 57 min",
        "description": "The missions of the Strategic Homeland Intervention, Enforcement and Logistics Division.\r\n- Season 3, Episode 11-18",
        "timeline": "March-April 2016",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Agents-of-S-H-I-E-L-D-"
    },
    {
        "position": 72,
        "title": "WHIH News Front",
        "year": "2015-2016",
        "runtime": "14 min",
        "description": "A series of news bulletins on events within the Marvel Cinematic Universe, as presented by reporter Christine Everhart.\r\n- Season 2",
        "timeline": "April-May 2016",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "WHIH-News-Front"
    },
    {
        "position": 73,
        "title": "The Defenders",
        "year": "2017",
        "runtime": "6 h 41 min",
        "description": "Set a few months after the events of the second season of Daredevil, and a month after the events of Iron Fist, the vigilantes Daredevil, Jessica Jones, Luke Cage, and Iron Fist team up in New York City to fight a common enemy: The Hand.\r\n- Season 1",
        "timeline": "May 2016",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "The-Defenders"
    },
    {
        "position": 74,
        "title": "Agents of S.H.I.E.L.D.",
        "year": "2013-2020",
        "runtime": "43 min",
        "description": "The missions of the Strategic Homeland Intervention, Enforcement and Logistics Division.\r\n- Season 3, Episode 19",
        "timeline": "June 2016",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Agents-of-S-H-I-E-L-D-"
    },
    {
        "position": 75,
        "title": "Captain America: Civil War",
        "year": "2016",
        "runtime": "2 h 31 min",
        "description": "Political involvement in the Avengers' affairs causes a rift between Captain America and Iron Man.",
        "timeline": "May-June 2016",
        "universe": "Earth-616",
        "phase": "Phase 3",
        "studio": "Marvel Studios",
        "image": "Captain-America-Civil-War"
    },
    {
        "position": 76,
        "title": "Agents of S.H.I.E.L.D.",
        "year": "2013-2020",
        "runtime": "2 h 14 min",
        "description": "The missions of the Strategic Homeland Intervention, Enforcement and Logistics Division.\r\n- Season 3, Episode 20-22",
        "timeline": "June 2016",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Agents-of-S-H-I-E-L-D-"
    },
    {
        "position": 77,
        "title": "Deadpool",
        "year": "2016",
        "runtime": "1 h 50 min",
        "description": "A wisecracking mercenary gets experimented on and becomes immortal yet hideously scarred, and sets out to track down the man who ruined his looks.",
        "timeline": "2016",
        "universe": "Earth-10005",
        "phase": "other",
        "studio": "20th Century Fox",
        "image": "Deadpool-"
    },
    {
        "position": 78,
        "title": "Black Widow",
        "year": "2021",
        "runtime": "2 h 16 min",
        "description": "Natasha Romanoff confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises.",
        "timeline": "June 2016",
        "universe": "Earth-616",
        "phase": "Phase 4",
        "studio": "Marvel Studios",
        "image": "Black-Widow"
    },
    {
        "position": 79,
        "title": "Black Panther",
        "year": "2018",
        "runtime": "2 h 18 min",
        "description": "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country's past.",
        "timeline": "June 2016",
        "universe": "Earth-616",
        "phase": "Phase 3",
        "studio": "Marvel Studios",
        "image": "Black-Panther"
    },
    {
        "position": 80,
        "title": "Inhumans",
        "year": "2017",
        "runtime": "5 h 56 min",
        "description": "An isolated community of superhumans fight to protect themselves.\r\n- Season 1",
        "timeline": "2016",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Inhumans"
    },
    {
        "position": 81,
        "title": "Spider-Man: Homecoming",
        "year": "2017",
        "runtime": "2 h 13 min",
        "description": "Peter Parker tries to stop Adrian 'The Vulture' Toomes from selling weapons made with advanced Chitauri technology while trying to balance his life as an ordinary high school student.",
        "timeline": "September 2016",
        "universe": "Earth-616",
        "phase": "Phase 3",
        "studio": "Marvel Studios",
        "image": "Spider-Man-Homecoming"
    },
    {
        "position": 82,
        "title": "The Punisher",
        "year": "2017-2019",
        "runtime": "11 h 39 min",
        "description": "After his revenge on those who murdered his family, aimless Marine veteran Frank Castle finds a new meaning in life as a vigilante known as The Punisher.\r\n- Season 1",
        "timeline": "November-December 2016",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "The-Punisher"
    },
    {
        "position": 83,
        "title": "Doctor Strange",
        "year": "2016",
        "runtime": "1 h 56 min",
        "description": "While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.",
        "timeline": "February 2016-February 2017",
        "universe": "Earth-616",
        "phase": "Phase 3",
        "studio": "Marvel Studios",
        "image": "Doctor-Strange"
    },
    {
        "position": 84,
        "title": "Cloak & Dagger",
        "year": "2018-2019",
        "runtime": "7 h 22 min",
        "description": "Two teenagers from very different backgrounds find themselves burdened and awakened to newly acquired superpowers while growing closer together every day.\r\n- Season 1",
        "timeline": "February-March 2017",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Cloak-Dagger"
    },
    {
        "position": 85,
        "title": "Agents of S.H.I.E.L.D.",
        "year": "2013-2020",
        "runtime": "5 h 55 min",
        "description": "The missions of the Strategic Homeland Intervention, Enforcement and Logistics Division.\r\n- Season 4, Episode 1-8",
        "timeline": "April 2017",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Agents-of-S-H-I-E-L-D-"
    },
    {
        "position": 86,
        "title": "Agents of S.H.I.E.L.D.: Slingshot",
        "year": "2016",
        "runtime": "27",
        "description": "Following Inhuman Yo-Yo Rodriguez also known as Slingshot on a personal Mission against time.",
        "timeline": "April 2017",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Agents-of-S-H-I-E-L-D-Slingshot"
    },
    {
        "position": 87,
        "title": "Agents of S.H.I.E.L.D.",
        "year": "2013-2020",
        "runtime": "2 h 58 min",
        "description": "The missions of the Strategic Homeland Intervention, Enforcement and Logistics Division.\r\n- Season 4, Episode 9-12",
        "timeline": "April 2017",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Agents-of-S-H-I-E-L-D-"
    },
    {
        "position": 88,
        "title": "Jessica Jones",
        "year": "2015-2019",
        "runtime": "11 h 16 min",
        "description": "Following the tragic end of her brief superhero career, Jessica Jones tries to rebuild her life as a private investigator, dealing with cases involving people with remarkable abilities in New York City.\r\n- Season 2",
        "timeline": "April-May 2017",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Jessica-Jones"
    },
    {
        "position": 89,
        "title": "Agents of S.H.I.E.L.D.",
        "year": "2013-2020",
        "runtime": "7 h 27 min",
        "description": "The missions of the Strategic Homeland Intervention, Enforcement and Logistics Division.\r\n- Season 4, Episode 13-22",
        "timeline": "May 2017",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Agents-of-S-H-I-E-L-D-"
    },
    {
        "position": 90,
        "title": "Luke Cage",
        "year": "2016-2018",
        "runtime": "12 h 42 min",
        "description": "When a sabotaged experiment gives him super strength and unbreakable skin, Luke Cage becomes a fugitive attempting to rebuild his life in Harlem and must confront his past and fight a battle for the heart of his city.\r\n- Season 2",
        "timeline": "August-September 2017",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Luke-Cage"
    },
    {
        "position": 91,
        "title": "Iron Fist",
        "year": "2017-2018",
        "runtime": "8 h 46 min",
        "description": "A young man is bestowed with incredible martial arts skills and a mystical force known as the Iron Fist.\r\n- Season 2",
        "timeline": "September 2017",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Iron-Fist"
    },
    {
        "position": 92,
        "title": "Daredevil 3",
        "year": "2015-2018",
        "runtime": "11 h 5 min",
        "description": "A blind lawyer by day, vigilante by night. Matt Murdock fights the crime of New York as Daredevil.\r\n- Season 3",
        "timeline": "October 2017",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Daredevil-3"
    },
    {
        "position": 93,
        "title": "Runaways",
        "year": "2017-2019",
        "runtime": "8 h 20 min",
        "description": "After discovering a dark secret about their parents, a group of teenagers band together to run away from their homes in order to atone for their parents' actions and to discover the secrets of their origins.\r\n- Season 1",
        "timeline": "October 2017",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Runaways"
    },
    {
        "position": 94,
        "title": "Cloak & Dagger",
        "year": "2018-2019",
        "runtime": "7 h 10 min",
        "description": "Two teenagers from very different backgrounds find themselves burdened and awakened to newly acquired superpowers while growing closer together every day.\r\n- Season 2",
        "timeline": "October-November 2017",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Cloak-Dagger"
    },
    {
        "position": 95,
        "title": "Runaways",
        "year": "2017-2019",
        "runtime": "14 h 50 min",
        "description": "After discovering a dark secret about their parents, a group of teenagers band together to run away from their homes in order to atone for their parents' actions and to discover the secrets of their origins.\r\n- Season 2 \r\n- Season 3 Ep. 1-4",
        "timeline": "October-November 2017",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Runaways"
    },
    {
        "position": 96,
        "title": "Thor: Ragnarok",
        "year": "2017",
        "runtime": "2 h 13 min",
        "description": "Imprisoned on the planet Sakaar, Thor must race against time to return to Asgard and stop Ragnarök, the destruction of his world, at the hands of the powerful and ruthless villain Hela.",
        "timeline": "November 2017",
        "universe": "Earth-616",
        "phase": "Phase 3",
        "studio": "Marvel Studios",
        "image": "Thor-Ragnarok"
    },
    {
        "position": 97,
        "title": "Agents of S.H.I.E.L.D.",
        "year": "2013-2020",
        "runtime": "7 h 24 min",
        "description": "The missions of the Strategic Homeland Intervention, Enforcement and Logistics Division.\r\n- Season 5, Episode 1-10",
        "timeline": "December 2017-February 2018",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Agents-of-S-H-I-E-L-D-"
    },
    {
        "position": 98,
        "title": "The New Mutans",
        "year": "2020",
        "runtime": "1 h 36 min",
        "description": "Five young mutants, just discovering their abilities while held in a secret facility against their will, fight to escape their past sins and save themselves.",
        "timeline": "2017",
        "universe": "Earth-10005",
        "phase": "other",
        "studio": "20th Century Fox",
        "image": "The-New-Mutans-"
    },
    {
        "position": 99,
        "title": "The Gifted 2",
        "year": "2017-2019",
        "runtime": "21 h 39 min",
        "description": "In a world where mutated humans are treated with distrust and fear, an institute for mutants battles to achieve peaceful co-existence with humanity.",
        "timeline": "2017-2018",
        "universe": "Earth-17372",
        "phase": "other",
        "studio": "20th Century Fox Television",
        "image": "The-Gifted-2"
    },
    {
        "position": 100,
        "title": "The Punisher  2",
        "year": "2017-2019",
        "runtime": "11 h 25 min",
        "description": "After his revenge on those who murdered his family, aimless Marine veteran Frank Castle finds a new meaning in life as a vigilante known as The Punisher.\r\n- Season 2",
        "timeline": "December 2017-January 2018",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "The-Punisher-2"
    },
    {
        "position": 101,
        "title": "Jessica Jones",
        "year": "2015-2019",
        "runtime": "10 h 59 min",
        "description": "Following the tragic end of her brief superhero career, Jessica Jones tries to rebuild her life as a private investigator, dealing with cases involving people with remarkable abilities in New York City.\r\n- Season 3",
        "timeline": "2018",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Jessica-Jones"
    },
    {
        "position": 102,
        "title": "Ant-Man and the Wasp",
        "year": "2018",
        "runtime": "2 h 2 min",
        "description": "As Scott Lang balances being both a superhero and a father, Hope van Dyne and Dr. Hank Pym present an urgent new mission that finds the Ant-Man fighting alongside The Wasp to uncover secrets from their past.",
        "timeline": "April-May 2018",
        "universe": "Earth-616",
        "phase": "Phase 3",
        "studio": "Marvel Studios",
        "image": "Ant-Man-and-the-Wasp"
    },
    {
        "position": 103,
        "title": "Runaways",
        "year": "2017-2019",
        "runtime": "5 h",
        "description": "After discovering a dark secret about their parents, a group of teenagers band together to run away from their homes in order to atone for their parents' actions and to discover the secrets of their origins.\r\n- Season 3, Episode 5-10",
        "timeline": "May 2018",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Runaways"
    },
    {
        "position": 104,
        "title": "Agents of S.H.I.E.L.D.",
        "year": "2013-2020",
        "runtime": "8 h 54 min",
        "description": "The missions of the Strategic Homeland Intervention, Enforcement and Logistics Division.\r\n- Season 5, Episode 11-22",
        "timeline": "May 2018",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Agents-of-S-H-I-E-L-D-"
    },
    {
        "position": 105,
        "title": "Avengers: Infinity War",
        "year": "2018",
        "runtime": "2 h 34 min",
        "description": "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",
        "timeline": "May 2018",
        "universe": "Earth-616",
        "phase": "Phase 3",
        "studio": "Marvel Studios",
        "image": "Avengers-Infinity-War"
    },
    {
        "position": 106,
        "title": "Deadpool  2",
        "year": "2018",
        "runtime": "2 h 1 min",
        "description": "Foul-mouthed mutant mercenary Wade Wilson (a.k.a. Deadpool) assembles a team of fellow mutant rogues to protect a young boy with abilities from the brutal, time-traveling cyborg Cable.",
        "timeline": "2018",
        "universe": "Earth-10005",
        "phase": "other",
        "studio": "20th Century Fox",
        "image": "Deadpool-2"
    },
    {
        "position": 107,
        "title": "Spider-Man: Into the Spider-Verse",
        "year": "2018",
        "runtime": "1 h 57 min",
        "description": "Teen Miles Morales becomes the Spider-Man of his universe and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.",
        "timeline": "2018",
        "universe": "Earth-1610B",
        "phase": "other",
        "studio": "Sony Pictures Animation",
        "image": "Spider-Man-Into-the-Spider-Verse"
    },
    {
        "position": 108,
        "title": "Venom",
        "year": "2018",
        "runtime": "1 h 52 min",
        "description": "A failed reporter is bonded to an alien entity, one of many symbiotes who have invaded Earth. But the being takes a liking to Earth and decides to protect it.",
        "timeline": "2018",
        "universe": "Earth-688B",
        "phase": "other",
        "studio": "Columbia Pictures",
        "image": "Venom"
    },
    {
        "position": 109,
        "title": "Venom: Let Tthere Be Carnage",
        "year": "2021",
        "runtime": "1 h 37 min",
        "description": "Eddie Brock attempts to reignite his career by interviewing serial killer Cletus Kasady, who becomes the host of the symbiote Carnage and escapes prison after a failed execution.",
        "timeline": "2018-2019",
        "universe": "Earth-688B",
        "phase": "other",
        "studio": "Columbia Pictures",
        "image": "Venom-Let-Tthere-Be-Carnage"
    },
    {
        "position": 110,
        "title": "Agents of S.H.I.E.L.D.",
        "year": "2013-2020",
        "runtime": "19 h 9 min",
        "description": "The missions of the Strategic Homeland Intervention, Enforcement and Logistics Division.\r\n- Season 6: January 2019 (9 h 36 min)\r\n- Season 7: Time Travel (1931-1983) then return to January 2019-2020 (9 h 33 min)",
        "timeline": "January 2019-2020",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Agents-of-S-H-I-E-L-D-"
    },
    {
        "position": 111,
        "title": "Helstrom",
        "year": "2020",
        "runtime": "8 h 36 min",
        "description": "Daimon and Ana Helstrom are the son and daughter of a mysterious and powerful serial killer. The siblings have a complicated dynamic as they track down the terrorizing worst of humanity - each with their attitude and skills.\r\n- Season 1",
        "timeline": "October-November 2020",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Television",
        "image": "Helstrom"
    },
    {
        "position": 112,
        "title": "Spider-Man: Across the Spider-Verse",
        "year": "2023",
        "runtime": "2 h 20 min",
        "description": "Traveling across the multiverse, Miles Morales meets a new team of Spider-People, made up of heroes from different dimensions. But when the heroes clash over how to deal with a new threat, Miles finds himself at a crossroads.",
        "timeline": "11 July 2023",
        "universe": "Earth-1610B",
        "phase": "other",
        "studio": "Sony Pictures Animation",
        "image": "Spider-Man-Across-the-Spider-Verse"
    },
    {
        "position": 113,
        "title": "Avengers: Endgame",
        "year": "2019",
        "runtime": "3 h 5 min",
        "description": "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
        "timeline": "October 2023",
        "universe": "Earth-616",
        "phase": "Phase 3",
        "studio": "Marvel Studios",
        "image": "Avengers-Endgame"
    },
    {
        "position": 114,
        "title": "Loki",
        "year": "2021-2023",
        "runtime": "5 h 3 min",
        "description": "The mercurial villain Loki resumes his role as the God of Mischief in a new series that takes place after the events of Avengers: Endgame.\r\n- Season 1",
        "timeline": "October 2023",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "Loki"
    },
    {
        "position": 115,
        "title": "What If...? 1",
        "year": "2021-2024",
        "runtime": "3 h 5 min",
        "description": "Exploring pivotal moments from the Marvel Cinematic Universe and turning them on their head, leading the audience into uncharted territory.\r\n- Season 1, Episode 1-5",
        "timeline": "After Loki",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios Animation",
        "image": "What-If-1"
    },
    {
        "position": 116,
        "title": "Marvel Zombies",
        "year": "2025-2026",
        "runtime": "2 h 17 min",
        "description": "After the Avengers are overtaken by a zombie plague, a group of survivors discover the key to bringing an end to the super-powered undead, racing across a dystopian landscape and risking their lives to save their world.\r\n- Season 1",
        "timeline": "After What If...? S01E05",
        "universe": "Earth-89521",
        "phase": "other",
        "studio": "Marvel Studios Animation",
        "image": "Marvel-Zombies"
    },
    {
        "position": 117,
        "title": "What If...? 1",
        "year": "2021-2024",
        "runtime": "3 h",
        "description": "Exploring pivotal moments from the Marvel Cinematic Universe and turning them on their head, leading the audience into uncharted territory.\r\n- Season 1, Episode 6-8 (1 h 48 min)\r\n- Season 2, Episode 4 (34 min)\r\n- Season 1, Episode 9 (38 min)",
        "timeline": "After Zombies",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios Animation",
        "image": "What-If-1"
    },
    {
        "position": 118,
        "title": "WandaVision",
        "year": "2021",
        "runtime": "6 h 6 min",
        "description": "Blends the style of classic sitcoms with the MCU, in which Wanda Maximoff and Vision - two super-powered beings living their ideal suburban lives - begin to suspect that everything is not as it seems.\r\n- Season 1",
        "timeline": "November 2023",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "WandaVision"
    },
    {
        "position": 119,
        "title": "Shang-Chi and the Legend of the Ten Rings",
        "year": "2021",
        "runtime": "2 h 15 min",
        "description": "Shang-Chi, the master of weaponry-based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization.",
        "timeline": "March-April 2024",
        "universe": "Earth-616",
        "phase": "Phase 4",
        "studio": "Marvel Studios",
        "image": "Shang-Chi-and-the-Legend-of-the-Ten-Rings"
    },
    {
        "position": 120,
        "title": "The Falcon and the Winter Soldier",
        "year": "2021",
        "runtime": "5 h 32 min",
        "description": "Following the events of 'Avengers: Endgame,' Sam Wilson/Falcon and Bucky Barnes/Winter Soldier team up in a global adventure that tests their abilities - and their patience.\r\n- Season 1",
        "timeline": "April-May 2024",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "The-Falcon-and-the-Winter-Soldier"
    },
    {
        "position": 121,
        "title": "Spider-Man: Far from Home",
        "year": "2019",
        "runtime": "2 h 9 min",
        "description": "Peter Parker heads to Europe hoping for a normal summer, but elemental attacks and a mysterious new hero pull him back into a dangerous fight he isn't ready to embrace.",
        "timeline": "June-July 2024",
        "universe": "Earth-616",
        "phase": "Phase 3",
        "studio": "Marvel Studios",
        "image": "Spider-Man-Far-from-Home"
    },
    {
        "position": 122,
        "title": "Morbius",
        "year": "2022",
        "runtime": "1 h 44 min",
        "description": "Biochemist Michael Morbius tries to cure himself of a rare blood disease, but he inadvertently infects himself with a form of vampirism instead.",
        "timeline": "2024",
        "universe": "Earth-688B",
        "phase": "other",
        "studio": "Columbia Pictures",
        "image": "Morbius"
    },
    {
        "position": 123,
        "title": "Eternals",
        "year": "2021",
        "runtime": "2 h 38 min",
        "description": "The saga of the Eternals, a race of immortal beings who lived on Earth and shaped its history and civilizations.",
        "timeline": "October 2024",
        "universe": "Earth-616",
        "phase": "Phase 4",
        "studio": "Marvel Studios",
        "image": "Eternals"
    },
    {
        "position": 124,
        "title": "Spider-Man: No Way Home",
        "year": "2021",
        "runtime": "2 h 28 min",
        "description": "Peter Parker turns to Doctor Strange after his identity destroys the life he knows, but a magical mistake draws powerful outsiders into his world and forces him to confront what being Spider Man really means.",
        "timeline": "July-December 2024",
        "universe": "Earth-616",
        "phase": "Phase 4",
        "studio": "Marvel Studios",
        "image": "Spider-Man-No-Way-Home"
    },
    {
        "position": 125,
        "title": "Venom: The Last Dance",
        "year": "2024",
        "runtime": "1 h 50 min",
        "description": "Eddie Brock and Venom must make a devastating decision as they're pursued by a mysterious military man and alien monsters from Venom's home world.",
        "timeline": "2024",
        "universe": "Earth-688B",
        "phase": "other",
        "studio": "Columbia Pictures",
        "image": "Venom-The-Last-Dance-"
    },
    {
        "position": 126,
        "title": "Doctor Strange in the Multiverse of Madness",
        "year": "2022",
        "runtime": "2 h 8 min",
        "description": "Doctor Strange teams up with a mysterious teenage girl who can travel across multiverses, to battle other-universe versions of himself which threaten to wipe out the multiverse. They seek help from the Scarlet Witch, Wong and others.",
        "timeline": "November-December 2024",
        "universe": "Earth-616",
        "phase": "Phase 4",
        "studio": "Marvel Studios",
        "image": "Doctor-Strange-in-the-Multiverse-of-Madness"
    },
    {
        "position": 127,
        "title": "Hawkeye",
        "year": "2021",
        "runtime": "5 h",
        "description": "Clint Barton aka Hawkeye has the mission to get back to his family for Christmas. But when a threat from his past shows up, Hawkeye reluctantly teams up with Kate Bishop, a skilled archer and his biggest fan, to unravel a conspiracy.\r\n- Season 1",
        "timeline": "December 2024",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "Hawkeye"
    },
    {
        "position": 128,
        "title": "Kraven the Hunter",
        "year": "2024",
        "runtime": "2 h 7 min",
        "description": "Kraven's complex relationship with his ruthless father, Nikolai Kravinoff, starts him down a path of vengeance with brutal consequences, motivating him to become not only the greatest hunter in the world, but also one of its most feared.",
        "timeline": "December 2024",
        "universe": "Earth-688B",
        "phase": "other",
        "studio": "Columbia Pictures",
        "image": "Kraven-the-Hunter"
    },
    {
        "position": 129,
        "title": "She-Hulk: Attorney at Law",
        "year": "2022",
        "runtime": "1 h 44 min",
        "description": "Jennifer Walters navigates the complicated life of a single, 30-something attorney who also happens to be a green 6-foot-7-inch superpowered Hulk.\r\n-  Season 1, Episode 1-3",
        "timeline": "2025",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "She-Hulk-Attorney-at-Law"
    },
    {
        "position": 130,
        "title": "Moon Knight",
        "year": "2022",
        "runtime": "5 h 5 min",
        "description": "Steven Grant discovers he's been granted the powers of an Egyptian moon god. But he soon finds out that these newfound powers can be both a blessing and a curse to his troubled life.\r\n- Season 1",
        "timeline": "April-May 2025",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "Moon-Knight"
    },
    {
        "position": 131,
        "title": "Black Panther: Wakanda Forever",
        "year": "2022",
        "runtime": "2 h 43 min",
        "description": "The people of Wakanda fight to protect their home from intervening world powers as they mourn the death of King T'Challa.",
        "timeline": "May 2025",
        "universe": "Earth-616",
        "phase": "Phase 4",
        "studio": "Marvel Studios",
        "image": "Black-Panther-Wakanda-Forever"
    },
    {
        "position": 132,
        "title": "Echo",
        "year": "2023-2024",
        "runtime": "3 h 35 min",
        "description": "Maya Lopez must face her past, reconnect with her Native American roots, and embrace the meaning of family and community if she ever hopes to move forward.\r\n- Season 1",
        "timeline": "May 2025",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "Echo"
    },
    {
        "position": 133,
        "title": "She-Hulk: Attorney at Law",
        "year": "2022",
        "runtime": "3 h 28 min",
        "description": "Jennifer Walters navigates the complicated life of a single, 30-something attorney who also happens to be a green 6-foot-7-inch superpowered Hulk.\r\n- Season 1, Episode 4-9",
        "timeline": "June-September 2025",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "She-Hulk-Attorney-at-Law"
    },
    {
        "position": 134,
        "title": "Ms. Marvel",
        "year": "2022",
        "runtime": "4 h 51 min",
        "description": "Kamala, a superhero fan with an imagination - particularly when it comes to Captain Marvel - feels like she doesn't fit in at school and sometimes even at home, that is until she gets superpowers like the heroes she admires.\r\n- Season 1",
        "timeline": "September 2025",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "Ms-Marvel"
    },
    {
        "position": 135,
        "title": "Ironheart",
        "year": "2025",
        "runtime": "1 h 35 min",
        "description": "Genius teenage inventor Riri Williams creates the most advanced suit of armor since Iron Man.\r\n- Season 1, Episode 1-2",
        "timeline": "September 2025",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "Ironheart"
    },
    {
        "position": 136,
        "title": "Thor: Love and Thunder",
        "year": "2022",
        "runtime": "2 h 1 min",
        "description": "Thor enlists the help of Valkyrie, Korg and ex-girlfriend Jane Foster to fight Gorr the God Butcher, who intends to make the gods extinct.",
        "timeline": "October 2025",
        "universe": "Earth-616",
        "phase": "Phase 4",
        "studio": "Marvel Studios",
        "image": "Thor-Love-and-Thunder"
    },
    {
        "position": 137,
        "title": "Ironheart",
        "year": "2025",
        "runtime": "3 h 31 min",
        "description": "Genius teenage inventor Riri Williams creates the most advanced suit of armor since Iron Man.\r\n- Season 1, Episode 3-6",
        "timeline": "October 2025",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "Ironheart"
    },
    {
        "position": 138,
        "title": "Werewolf by Night",
        "year": "2022",
        "runtime": "55 min",
        "description": "Follows a lycanthrope superhero who fights evil using the abilities given to him by a curse brought on by his bloodline.",
        "timeline": "October-November 2025",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "Werewolf-by-Night"
    },
    {
        "position": 139,
        "title": "The Guardians of the Galaxy Holiday Special",
        "year": "2022",
        "runtime": "45 min",
        "description": "Star-Lord, Drax, Rocket, Mantis, and Groot engage in some spirited shenanigans in an all-new original special created for Disney+.",
        "timeline": "December 2025",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "The-Guardians-of-the-Galaxy-Holiday-Special"
    },
    {
        "position": 140,
        "title": "Ant-Man and the Wasp: Quantumania",
        "year": "2023",
        "runtime": "2 h 6 min",
        "description": "Scott Lang and Hope Van Dyne are dragged into the Quantum Realm, along with Hope's parents and Scott's daughter Cassie. Together they must find a way to escape, but what secrets is Hope's mother hiding? And who is the mysterious Kang?",
        "timeline": "July 2026",
        "universe": "Earth-616",
        "phase": "Phase 5",
        "studio": "Marvel Studios",
        "image": "Ant-Man-and-the-Wasp-Quantumania"
    },
    {
        "position": 141,
        "title": "Guardians of the Galaxy Vol. 3",
        "year": "2023",
        "runtime": "2 h 32 min",
        "description": "Still reeling from the loss of Gamora, Peter Quill rallies his team to defend the universe and one of their own - a mission that could mean the end of the Guardians if not successful.",
        "timeline": "2026",
        "universe": "Earth-616",
        "phase": "Phase 5",
        "studio": "Marvel Studios",
        "image": "Guardians-of-the-Galaxy-Vol-3"
    },
    {
        "position": 142,
        "title": "Secret Invasion",
        "year": "2023",
        "runtime": "4 h 32 min",
        "description": "Fury and Talos try to stop the Skrulls who have infiltrated the highest spheres of the Marvel Universe.\r\n- Season 1",
        "timeline": "October-November 2026",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "Secret-Invasion"
    },
    {
        "position": 143,
        "title": "The Marvels",
        "year": "2023",
        "runtime": "1 h 46 min",
        "description": "Carol Danvers gets her powers entangled with those of Kamala Khan and Monica Rambeau, forcing them to work together to save the universe.",
        "timeline": "November 2026",
        "universe": "Earth-616",
        "phase": "Phase 5",
        "studio": "Marvel Studios",
        "image": "The-Marvels"
    },
    {
        "position": 144,
        "title": "Loki",
        "year": "2021-2023",
        "runtime": "5 h 13 min",
        "description": "The mercurial villain Loki resumes his role as the God of Mischief in a new series that takes place after the events of Avengers: Endgame.\r\n- Season 2",
        "timeline": "After The Marvels",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "Loki"
    },
    {
        "position": 145,
        "title": "What If...? 2",
        "year": "2021-2024",
        "runtime": "4 h 18 min",
        "description": "Exploring pivotal moments from the Marvel Cinematic Universe and turning them on their head, leading the audience into uncharted territory.\r\n- Season 2, Episode 1-3 \r\n- Season 2, Episode 5-9",
        "timeline": "After Loki 2",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios Animation",
        "image": "What-If-2"
    },
    {
        "position": 146,
        "title": "Deadpool & Wolverine",
        "year": "2024",
        "runtime": "2 h 10 min",
        "description": "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.\r\nDeadpool (Earth-10005) visits Earth-616/TVA/Void.\r\nWatch after Loki 2.",
        "timeline": "November 2024",
        "universe": "Earth-616",
        "phase": "Phase 5",
        "studio": "Marvel Studios",
        "image": "Deadpool-Wolverine"
    },
    {
        "position": 147,
        "title": "Agatha All Along",
        "year": "2024",
        "runtime": "6 h 20 min",
        "description": "A spell-bound Agatha Harkness regains freedom thanks to a teen's help. Intrigued by his plea, she embarks on the Witches' Road trials to reclaim her powers and discover the teen's motivations.\r\n- Season 1",
        "timeline": "November 2026",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "Agatha-All-Along"
    },
    {
        "position": 148,
        "title": "What If...? 3",
        "year": "2021-2024",
        "runtime": "4 h 14 min",
        "description": "Exploring pivotal moments from the Marvel Cinematic Universe and turning them on their head, leading the audience into uncharted territory.\r\n- Season 3",
        "timeline": "After Agatha All Along",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios Animation",
        "image": "What-If-3"
    },
    {
        "position": 149,
        "title": "Daredevil: Born Again",
        "year": "2025-",
        "runtime": "7 h 34 min",
        "description": "Matt Murdock finds himself on a collision course with Wilson Fisk when their past identities begin to emerge.\r\n- Season 1",
        "timeline": "December 2026-April 2027",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "Daredevil-Born-Again"
    },
    {
        "position": 150,
        "title": "Captain America: Brave New World",
        "year": "2025",
        "runtime": "2 h",
        "description": "Sam Wilson, the new Captain America, finds himself in the middle of an international incident and must discover the motive behind a nefarious global plan.",
        "timeline": "April 2027",
        "universe": "Earth-616",
        "phase": "Phase 5",
        "studio": "Marvel Studios",
        "image": "Captain-America-Brave-New-World"
    },
    {
        "position": 151,
        "title": "Wonder Man",
        "year": "2026",
        "runtime": "4 h 27 min",
        "description": "Small-time actor Simon Williams struggles to reckon with his personal life while hiding his super-powers as he tries to land his dream role. Meanwhile, a shady government agent leverages a new friendship in order to save his own job.\r\n- Season 1",
        "timeline": "April 2027",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "Wonder-Man"
    },
    {
        "position": 152,
        "title": "Thunderbolts*",
        "year": "2025",
        "runtime": "2 h 8 min",
        "description": "After finding themselves ensnared in a death trap, an unconventional team of antiheroes must go on a dangerous mission that will force them to confront the darkest corners of their pasts.",
        "timeline": "September 2027",
        "universe": "Earth-616",
        "phase": "Phase 5",
        "studio": "Marvel Studios",
        "image": "Thunderbolts-"
    },
    {
        "position": 153,
        "title": "Daredevil: Born Again 2",
        "year": "2025-",
        "runtime": "6 h 54 min",
        "description": "Matt Murdock finds himself on a collision course with Wilson Fisk when their past identities begin to emerge.\r\n- Season 2",
        "timeline": "October-November 2027",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "Daredevil-Born-Again-2"
    },
    {
        "position": 154,
        "title": "The Punisher: One Last Kill",
        "year": "2026",
        "runtime": "51 min",
        "description": "Frank Castle retreats from violence after years of loss, but a criminal bounty drags him back into a brutal fight that forces him to confront what remains of his purpose.",
        "timeline": "September 2028",
        "universe": "Earth-616",
        "phase": "other",
        "studio": "Marvel Studios",
        "image": "The-Punisher-One-Last-Kill"
    },
    {
        "position": 155,
        "title": "Spider-Man: Brand New Day",
        "year": "2026",
        "runtime": "2 h 25 min",
        "description": "A forgotten Peter Parker lives alone as a full-time Spider-Man until mounting pressure triggers a dangerous change and a powerful new enemy emerges.",
        "timeline": "October 2028",
        "universe": "Earth-616",
        "phase": "Phase 6",
        "studio": "Marvel Studios",
        "image": "Spider-Man-Brand-New-Day"
    },
    {
        "position": 156,
        "title": "Avengers: Doomsday",
        "year": "2026",
        "runtime": "2 h 45 min",
        "description": "Heroes from three different worlds must unite when they're thrust together to confront a catastrophic danger that could destroy everything they know.",
        "timeline": "2028",
        "universe": "Earth-616",
        "phase": "Phase 6",
        "studio": "Marvel Studios",
        "image": "Avengers-Doomsday"
    },
    {
        "position": 157,
        "title": "Logan",
        "year": "2017",
        "runtime": "2 h 19 min",
        "description": "In a future where mutants are nearly extinct, an elderly and weary Logan leads a quiet life. But when Laura, a mutant child pursued by scientists, comes to him for help, he must get her to safety.",
        "timeline": "2029",
        "universe": "Earth-17315",
        "phase": "other",
        "studio": "20th Century Fox",
        "image": "Logan"
    },
];